import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@keka/db";
import { PERMISSIONS as P, canAccessEmployee } from "@keka/rbac";
import { formatDate } from "@keka/shared";
import { EMPLOYEE_VISIBLE, LETTER_STATUS_LABEL, LETTER_WORKFLOWS, hashBody } from "@keka/services";
import { requireViewer, can } from "@/lib/context";
import { PageHead, Card, Badge, Callout } from "@/components/ui";
import { LETTER_TONE } from "../tone";
import { LetterFrame, DecideLetter, VoidLetter, AcknowledgeLetter, SignLetter } from "../forms";

/** One generated letter: its text, where it is in its workflow, and the action that is yours. */
export default async function LetterPage({ params }: { params: Promise<{ id: string }> }) {
  const viewer = await requireViewer();
  const { id } = await params;
  const doc = await prisma.generatedDocument.findFirst({
    where: { id, employee: { tenantId: viewer.tenantId } },
    include: {
      template: { select: { name: true } },
      employee: { select: { id: true, displayName: true, employeeNumber: true, departmentId: true, locationId: true, legalEntityId: true, businessUnitId: true, reportingManagerId: true } },
    },
  });
  if (!doc) notFound();
  const own = doc.employeeId === viewer.employee?.id;
  const hr = can(viewer, P.LETTER_GENERATE) && canAccessEmployee(viewer, doc.employee, P.LETTER_GENERATE);
  // An employee sees their letter only once HR has released it.
  if (!hr && !(own && EMPLOYEE_VISIBLE.includes(doc.status))) notFound();
  const approver = hr && can(viewer, P.DOCUMENT_TEMPLATE_MANAGE) && doc.issuedByUserId !== viewer.user.id;
  const users = await prisma.user.findMany({ where: { id: { in: [doc.issuedByUserId, doc.approvedBy].filter((u): u is string => !!u) } }, select: { id: true, email: true, employee: { select: { displayName: true } } } });
  const who = (u: string | null) => { const r = users.find((x) => x.id === u); return r?.employee?.displayName ?? r?.email ?? "—"; };
  const intact = !doc.contentHash || doc.contentHash === hashBody(doc.renderedBody);

  return (
    <>
      <PageHead
        title={doc.template.name}
        subtitle={`${doc.employee.displayName} (${doc.employee.employeeNumber}) · generated ${formatDate(doc.issuedOn)}`}
        actions={<div className="row gap-2"><Link className="btn ghost" href={own && !hr ? "/documents?tab=mine" : "/documents?tab=letters"}>Back</Link><a className="btn" href={`/documents/letters/${doc.id}/print`} target="_blank" rel="noreferrer">Print or save as PDF</a></div>}
      />
      {!intact ? <div style={{ marginBottom: 16 }}><Callout tone="danger" title="This letter's text does not match its fingerprint">It has been changed since it was generated and cannot be signed. Withdraw it and generate it again.</Callout></div> : null}
      <div className="grid" style={{ gridTemplateColumns: "minmax(0, 2fr) minmax(260px, 1fr)", gap: 18, alignItems: "start" }}>
        <LetterFrame html={doc.renderedBody} height={640} />
        <div className="stack gap-4">
          <Card title="Status">
            <div className="stack gap-2 text-sm">
              <div><Badge tone={LETTER_TONE[doc.status] ?? "neutral"}>{LETTER_STATUS_LABEL[doc.status] ?? doc.status.toLowerCase()}</Badge></div>
              <div className="subtle">Workflow: {LETTER_WORKFLOWS[(doc.workflow ?? "") as keyof typeof LETTER_WORKFLOWS] ?? doc.workflow}</div>
              {hr ? <div>Generated by {who(doc.issuedByUserId)}</div> : null}
              {doc.approvedAt && hr ? <div>{doc.status === "REJECTED" ? "Rejected" : "Approved"} by {who(doc.approvedBy)} on {formatDate(doc.approvedAt)}{doc.decisionNote ? `: ${doc.decisionNote}` : ""}</div> : null}
              {doc.acknowledgedAt ? <div>Acknowledged on {formatDate(doc.acknowledgedAt)}</div> : null}
              {doc.signedAt ? <div>Signed as “{doc.signerName}” on {doc.signedAt.toISOString().slice(0, 16).replace("T", " ")} UTC{doc.signedIp ? ` from ${doc.signedIp}` : ""}</div> : null}
              {doc.voidedAt ? <div className="neg">Withdrawn on {formatDate(doc.voidedAt)}: {doc.voidReason}</div> : null}
              {doc.contentHash ? <div className="text-xs subtle mono" style={{ wordBreak: "break-all" }}>Fingerprint {doc.contentHash.slice(0, 16)}…</div> : null}
            </div>
          </Card>
          {doc.status === "PENDING_APPROVAL" && approver ? <Card title="Approve this letter"><DecideLetter id={doc.id} /></Card> : null}
          {doc.status === "PENDING_APPROVAL" && hr && !approver ? <Callout tone="info" title="Waiting for approval">Someone with template rights, other than whoever generated it, approves it before the employee sees it.</Callout> : null}
          {own && doc.status === "PENDING_ACKNOWLEDGEMENT" ? <Card title="Acknowledge"><AcknowledgeLetter id={doc.id} /></Card> : null}
          {own && doc.status === "PENDING_SIGNATURE" && intact ? <Card title="Sign this letter"><SignLetter id={doc.id} name={doc.employee.displayName ?? ""} /></Card> : null}
          {hr && !["VOID", "REJECTED"].includes(doc.status) ? <VoidLetter id={doc.id} /> : null}
        </div>
      </div>
    </>
  );
}
